---
title: "bpc_draft"
author: "XITONG HE(29026342)"
date: "16/05/2021"
output: html_document
editor_options: 
  chunk_output_type: inline
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,message = FALSE,warning = FALSE)
```

```{r}
library(tidyverse)
library(bpcs)
library(rstan)
library(rvest)

```


```{r read-tennis-data}
atp_results <- readRDS(here::here("data/atp_results.rds"))%>%
  filter(Retired!="TRUE",Walkover!="TRUE")

atp_results%>%
  select(Player1,Player2)%>%
  rename(player0=Player1,player1=Player2)%>%
  mutate(y=as.numeric(0))->atp_results

wta_results <- readRDS(here::here("data/wta_results.rds"))%>%
  filter(Retired!="TRUE",Walkover!="TRUE")

wta_results%>%
  select(Player1,Player2)%>%
  rename(player0=Player1,player1=Player2)%>%
  mutate(y=as.numeric(0))->wta_results
```


```{r read-tennis-ranking}
atp_html <- read_html(here::here("data/ATP_Tennis.html"))
atp_rankings <- html_node(atp_html, "table") %>% html_table(fill=TRUE) 
# There is only one table in page so use html_node rather than html_nodes
atp_rankings <- atp_rankings %>% 
  janitor::remove_empty() %>% 
  dplyr::as_tibble()
atp_rankings


wta_html <- read_html(here::here("data/WTA_Tennis.html"))


wta_rankings <- html_node(wta_html, "table") %>% html_table(fill=TRUE) 
wta_rankings <- wta_rankings %>% 
  janitor::remove_empty() %>% 
  as_tibble()%>%
  head(100)
wta_rankings


```

```{r top-100-tennis-players}
atp_results%>%
  filter(player0%in%atp_rankings$Player&player1%in%atp_rankings$Player)->atp_top_100

wta_results%>%
  filter(player0%in%wta_rankings$PLAYER&player1%in%wta_rankings$PLAYER)->wta_top_100
```


```{r stan-data-function}
make_stan_data <- function(data, win, player0, player1){
  
  players <- unique(c(data[,player0], data[,player1]))
  index <- order(players)
  names(index) <- players
  
  model_data  = list(
    index = index,
    y = data[,win],
    player0_indexes = index[data$player0],
    player1_indexes = index[data$player1],
    N_total = nrow(data),
    N_players = max(index)
  )
}


model_data_atp <- make_stan_data(atp_top_100, "y", "player0", "player1")
model_data_wta <- make_stan_data(wta_top_100, "y", "player0", "player1")

model <- rstan::stan_model("bpc_h2h.stan")
```


```{r stan-model}
# Use VB for testing
atp_fit_model <- rstan::vb(model, 
                           data = model_data_atp,
                           tol_rel_obj = 0.001)

# Use Sampling for testing
atp_fit <- rstan::sampling(model, 
                           data = model_data_atp)


wta_fit_model <- rstan::vb(model, 
                           data = model_data_wta,
                           tol_rel_obj = 0.001)
wta_fit <- rstan::sampling(model, 
                           data = model_data_wta)


```


```{r coefficient-stan-model}

h2h<-summary(atp_fit, pars = "h2h")$summary%>%
  as.data.frame()%>%
  rownames_to_column(var = "h2h")

atp_fit_summary <- summary(atp_fit)$summary %>% 
  as.data.frame() %>% 
  mutate(variable = rownames(.)) %>% 
  select(variable, everything()) %>% 
  as_data_frame()

#VB model

# h2h_model<-summary(fit_model, pars = "h2h")$summary%>%
#   as.data.frame()%>%
#   rownames_to_column(var = "h2h")

fit_mcmc <- fit %>% 
  rstan::extract()


wta_fit_summary <- summary(wta_fit)$summary %>% 
  as.data.frame() %>% 
  mutate(variable = rownames(.)) %>% 
  select(variable, everything()) %>% 
  as_data_frame()


wta_h2h<-summary(wta_fit, pars = "h2h")$summary%>%
  as.data.frame()%>%
  rownames_to_column(var = "h2h")
```

```{r check-diagnostics}


fit_summary %>% 
  ggplot(aes(n_eff)) + 
  geom_histogram(bins = 30) + 
  geom_vline(aes(xintercept = 4000), color = 'red')

#The Rhat statistic helps tell us whether these parameters are so poorly sampled that we have a problem. More or less Rhat tells you whether or not each of the chains has reached a stable posterior distribution, despite starting at different starting values. Gelman recommends that Rhat for each parameter be less than 1.1

fit_summary %>% 
  ggplot(aes(Rhat)) + 
  geom_histogram(bins = 30) + 
  geom_vline(aes(xintercept = 1.1), color = 'red')


# check the h2h effect whether it is concentrated at 0
fit_summary %>% 
  filter(str_detect(variable,"h2h\\["))%>%
  summarise(mean=mean(mean),`2.5%`=mean(`2.5%`),`97.5%`=mean(`97.5%`),`25%`=mean(`25%`),`75%`=mean(`75%`))%>%
  mutate(variable=paste("h2h"))%>%
  ggplot() + 
  geom_linerange(aes(variable, ymin = `2.5%`,ymax = `97.5%`)) + 
  geom_crossbar(aes(variable, mean, ymin = `25%`, ymax = `75%`), fill= 'grey') 

wta_fit_summary %>% 
  ggplot(aes(n_eff)) + 
  geom_histogram(bins = 30) + 
  geom_vline(aes(xintercept = 4000), color = 'red')

wta_fit_summary %>% 
  ggplot(aes(Rhat)) + 
  geom_histogram(bins=30) + 
  geom_vline(aes(xintercept = 1.1), color = 'red')


wta_fit_summary %>% 
  filter(str_detect(variable,"h2h\\["))%>%
  summarise(mean=mean(mean),`2.5%`=mean(`2.5%`),`97.5%`=mean(`97.5%`),`25%`=mean(`25%`),`75%`=mean(`75%`))%>%
  mutate(variable=paste("h2h"))%>%
  ggplot() + 
  geom_linerange(aes(variable, ymin = `2.5%`,ymax = `97.5%`)) + 
  geom_crossbar(aes(variable, mean, ymin = `25%`, ymax = `75%`), fill= 'grey') 

```